### ISSUE TITLE
Team membership: 'team size' has wrong styling

### ISSUE THREAD

**Issue by bartv42** [bartv42/cloudshop#1]
The word 'team size' is a white font on a white background (hightlighted in the attachment for clarity)

https://store.blender.org/product/blender-cloud-team/

![blender_cloud_team_membership___blender_store](https://cloud.githubusercontent.com/assets/6816469/3702130/8a56db9e-13fb-11e4-8f5c-c2922d85a17c.png)

**Comment by venomgfx** [comment]
Fixed on 1c7be14
