### ISSUE TITLE
Broken workflow for manual subscription creation

### ISSUE THREAD

**Issue by fsiddi** [bartv42/cloudshop#10]
Currently it seems not possible to manually assign a subscription to a user. I'm not sure how we should handle free trial, sign up fee, payment methods and so on.

**Comment by bartv42** [comment]
Deployed to production. Still to do: document this workflow.

**Comment by bartv42** [comment]
Documentation available; please review:

https://docs.google.com/document/d/143zRqEbNDX-oxOcvAFn5KyI3n5vW2mKNkGBh3nAZec4/edit

**Comment by fsiddi** [comment]
Docs seem clear! I'm going to try this later today.

**Comment by fsiddi** [comment]
This seems to work ok for the moment, so I'll archive.
