### ISSUE TITLE
Hundreds of subscriptions imported as cancelled

### ISSUE THREAD

**Issue by fsiddi** [bartv42/cloudshop#15]
Maybe we can fix this by setting them all to active and letting the system to figure out what to mark as on hold.

**Comment by bartv42** [comment]
I manually reactivated 10 accounts, and set their next payment date to tomorrow. This is the list of accounts:

(see email for list)

Tomorrow, I will check if anyone actually renewed, and if the next payment has been correctly updated to (tomorrow+1 month). If it does, I will create a short document describing how to we need to reprocess these subscriptions.

Bart

**Comment by bartv42** [comment]
Check failed; as discussed I'm now exporting all originally imported users with a renewing subscription who are inactive.
