### ISSUE TITLE
Checkout page shows incorrect login form

### ISSUE THREAD

**Issue by bartv42** [bartv42/cloudshop#27]

**Comment by bartv42** [comment]
Reported by Ton:

Logout, and order cloud, then click on "checkout" (not 'view cart')
The store says "go to the Billing & Shipping section". Which does not exist.

With some fiddling you can find out how to make an account, but It then takes at least three steps to make an 'ID'.

At least the text should say prominently "Make a new account ("Blender ID") here" or so.

**Comment by bartv42** [comment]
This page is now using the same form as /my-account. Please review.

**Comment by tonroosendaal** [comment]
Looks good!
