### ISSUE TITLE
Remove "related products" 

### ISSUE THREAD

**Issue by tonroosendaal** [bartv42/cloudshop#29]
If you buy cloud you don't want a recommendation to buy the team cloud option.

http://wordpress.org/support/topic/remove-related-products-from-bottom-of-product-pages

**Comment by bartv42** [comment]
Thanks Ton! I've deployed the change. Please note that:
- you can't check this until the new Team subscription becomes visible again
- this code removes _all_ related products, also from other future store products. If we need something more selective by then (don't show related products for Cloud products, but do show them for t-shirts etc), I need to dive in.
