### ISSUE TITLE
Import: cloud_expiration_date contains invalid date

### ISSUE THREAD

**Issue by bartv42** [bartv42/cloudshop#3]
https://store.blender.org/wp-admin/post.php?post=331&action=edit

Order 20140309-SOF-1-CLD

![schermafbeelding 2014-07-25 om 15 08 46](https://cloud.githubusercontent.com/assets/6816469/3702233/d4b9c074-13fc-11e4-8f55-0c59be1b88b0.png)

**Comment by fsiddi** [comment]
Should be fixed, I wait for confirmation.

**Comment by fsiddi** [comment]
Hi there, could you confirm that this was fixed?

**Comment by bartv42** [comment]
Fixed.
