### ISSUE TITLE
Clearer login text

### ISSUE THREAD

**Issue by fsiddi** [bartv42/cloudshop#7]
In https://store.blender.org/my-account/ it would be great to have a clearer text before the form. Something like:

```
In order to login to the store you need  Blender-ID. No Blender-ID? Get one here!
```

The links should point to:
- http://www.blender.org/id/register
- http://www.blender.org/id/reset

**Comment by bartv42** [comment]
I've updated the copy on the login form, please review.

**Comment by fsiddi** [comment]
Could you please: 
- move the text _before_ the form
- update the links to point to http://www.blender.org/id/register and http://www.blender.org/id/reset (not to the cloud)

**Comment by bartv42** [comment]
Updated, please review.

**Comment by fsiddi** [comment]
Perfect, thanks.
